#!/bin/bash

echo "🔑 Setting up GitHub Personal Access Token (PAT) for deployment..."
echo ""
echo "📋 Step 1: Create a PAT token"
echo "1. Go to: https://github.com/settings/tokens"
echo "2. Click 'Generate new token' → 'Generate new token (classic)'"
echo "3. Name: 'Event Org Deployment'"
echo "4. Expiration: '90 days'"
echo "5. Scopes: ✅ repo, ✅ workflow"
echo "6. Click 'Generate token'"
echo "7. COPY THE TOKEN (you won't see it again!)"
echo ""
echo "📋 Step 2: Use the token"
echo "Run this command with your token:"
echo "git remote set-url origin https://YOUR_TOKEN@github.com/ashishdavda35/event-org.git"
echo ""
echo "📋 Step 3: Push to GitHub"
echo "git push -u origin main"
echo ""
echo "📋 Step 4: Deploy to Vercel"
echo "1. Go to https://vercel.com"
echo "2. Import your GitHub repository"
echo "3. Deploy both frontend and backend"
echo ""
echo "🎯 Expected URLs:"
echo "Frontend: https://event-org-frontend.vercel.app"
echo "Backend: https://event-org-backend.vercel.app"
echo "Live Demo: https://event-org-frontend.vercel.app/poll/U706KM/results-fixed"
echo ""
echo "📖 See GITHUB_PAT_SETUP.md for detailed instructions"
