#!/bin/bash

echo "🚀 Setting up Event Org for Deployment..."

# Create initial commit
echo "📝 Creating initial commit..."
git add .
git commit -m "Initial commit: Event Org with live polling dashboard"

echo ""
echo "✅ Repository ready for deployment!"
echo ""
echo "📋 Next Steps:"
echo "1. Create GitHub repository:"
echo "   - Go to https://github.com/new"
echo "   - Name it 'event-org'"
echo "   - Don't initialize with README"
echo ""
echo "2. Push to GitHub:"
echo "   git remote add origin https://github.com/YOUR_USERNAME/event-org.git"
echo "   git push -u origin main"
echo ""
echo "3. Deploy to Vercel:"
echo "   - Go to https://vercel.com"
echo "   - Sign up with GitHub"
echo "   - Import your repository"
echo "   - Deploy both frontend and backend"
echo ""
echo "4. Set up MongoDB Atlas:"
echo "   - Go to https://mongodb.com/atlas"
echo "   - Create free cluster"
echo "   - Get connection string"
echo "   - Add to Vercel environment variables"
echo ""
echo "🎯 Expected URLs:"
echo "   Frontend: https://event-org-app.vercel.app"
echo "   Backend: https://event-org-backend.vercel.app"
echo "   Live Demo: https://event-org-app.vercel.app/poll/U706KM/results-fixed"
echo ""
echo "📖 See QUICK_DEPLOYMENT.md for detailed instructions"
